# Generated by Django 5.1.7 on 2025-05-02 22:04

import homework.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_person_icecream_icecreamkiosk_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, validators=[homework.models.validate_phone])),
            ],
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[homework.models.validate_positive])),
            ],
        ),
        migrations.RemoveField(
            model_name='icecreamkiosk',
            name='ice_creams',
        ),
        migrations.AddField(
            model_name='icecreamkiosk',
            name='ice_creams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
